---
- hosts: localhost
  become: true
  become_method: sudo
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - nginx
    - memcached
    - mysql
    - php7
    - xdebug
    - composer
